language:
  python

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report term --cov=./

env:
 - CODECOV_TOKEN=1dd387c2-ef8b-43f8-8bed-f5483f8d759a

after_success:
  - codecov

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA35M2EOCBLDHOSP6W"s
  secret_access_key: "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"
  region: "us-east-1"
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elasticbeanstalk-group17"
  on:
    branch: main