language:
  python

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report term --cov=./

env:
 - CODECOV_TOKEN=1dd387c2-ef8b-43f8-8bed-f5483f8d759a

after_success:
  - codecov

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA5HRW2O2SEI52FZTU"
  secret_access_key: "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"
  region: "us-east-1"
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elasticbeanstalk-group17"
  on:
    branch: main